### ISSUE TITLE
Metadata issue with Jsawyer Ultimate Edition and Unofficial Patch NVSE Plus

### ISSUE THREAD

**Issue by MoerasGrizzly** [loot/falloutnv#108]
[Unofficial Patch NVSE Plus](https://www.nexusmods.com/newvegas/mods/71239)
[JSawyer Ultimate Edition](https://www.nexusmods.com/newvegas/mods/61592)

[Same issue with UPP+ reported here](https://github.com/loot/falloutnv/issues/101), but UPNVSE+ replaces and supercedes UPP.

Additionally, UPNVSE+ should probably be part of group "Fixes and Resources"

**Comment by sibir-ine** [comment]
- [x] UP+: useInstead UPNVSE+
- [x] UPNVSE: useInstead UPNVSE+
- [x] Add UPNVSE+: fixesGroup, after YUP

**Comment by sibir-ine** [comment]
@MoerasGrizzly Done, thanks for the report!
