### ISSUE TITLE
NevadaSkies.esp should be part of group "Weather & Lighting"

### ISSUE THREAD

**Issue by MoerasGrizzly** [loot/falloutnv#109]
[Nevada Skies](https://www.nexusmods.com/newvegas/mods/35998) is currently a single-esp weather mod. However, LOOT does not recognize it as such and places it in the middle of the load order. It's currently part of no groups, but should be part of group Weather & Lighting.

**Comment by Pickysaurus** [comment]
I was just about to say this mod complains that "LOOT doesn't sort it properly" but it doesn't look like it's even in the master list, so +1 to this change.

**Comment by pStyl3** [comment]
LOOT already had some data on the plugin, just not a group assignment. I've added it, thanks for the report.
