### ISSUE TITLE
Mission Mojave - Ultimate Edition

### ISSUE THREAD

**Issue by sibir-ine** [loot/falloutnv#157]
[MMUE](https://www.nexusmods.com/newvegas/mods/45104/) & [MMUE Plus](https://www.nexusmods.com/newvegas/mods/47014/) were both hidden recently, so they'll have to be removed from the masterlist. There are various patches for them & other mods, so it'd be wise to remove references to them as well.

@TsunaMoo I'm sorry about the whole situation, but would it be possible for you to provide us with a list of the names of the plugins provided on both pages so we can find them more easily?

**Comment by MacSplody** [comment]
https://www.nexusmods.com/newvegas/mods/45104/ is visible at the moment.

Quick look and most of the patches start with `MMUE-`.

**Comment by sibir-ine** [comment]
Oh, cool, thanks! I'll download everything just in case & take a look in a moment. However, if it'll continue to stay up, instead of removing its metadata, we should replace the `*useInsteadYUP` messages with incompatibilities for YUP instead. I'll take a look at what other metadata should be updated as well as I see some load rules for mods that are no longer available.

**Comment by sibir-ine** [comment]
I was planning on giving it a bit more time to see if MMUE+ gets relisted as well, but, considering the only metadata we have on it is a `*useInsteadYUP` message & a `NoMerge` tag, neither of which are probably necessary, I'll just remove it after I finish updating MMUE.
