### ISSUE TITLE
White Screen & New Vegas

### ISSUE THREAD

**Issue by abysskeeper** [loot/falloutnv#225]
I've been trying to fix this for a few days now, I've tried pretty much every solution I could've found online but none of them worked!
Whenever I'm trying to run LOOT, either through MO2 or alone, I only get this white screen and inside the debug file it reads that it can't detect the game.
[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/7213368/LOOTDebugLog.txt)

Thanks in advance.

**Comment by pStyl3** [comment]
You can try the following. Create a shortcut of LOOT.exe, rightclick on the shortcut, select Properties. In the "Shortcut" window, add the following parameter at the end of the "Target" field (without the ""):
" --disable-gpu"

Notice the leading empty space. You should get something like this:
`D:\Modding\Programs\LOOT\LOOT.exe --disable-gpu`

**Comment by abysskeeper** [comment]
> 
> 
> You can try the following. Create a shortcut of LOOT.exe, rightclick on the shortcut, select Properties. In the "Shortcut" window, add the following parameter at the end of the "Target" field (without the ""):
> " --disable-gpu"
> 
> Notice the leading empty space. You should get something like this:
> `D:\Modding\Programs\LOOT\LOOT.exe --disable-gpu`

Thank you! I've managed to run LOOT but It still does not detect the game itself.
![l00t](https://user-images.githubusercontent.com/76806320/134424251-4013ca4e-ff6d-4a45-a0f0-f78928a09977.png)

**Comment by pStyl3** [comment]
Have you run FNV's launcher from Steam at least once?

**Comment by abysskeeper** [comment]
> 
> 
> Have you run FNV's launcher from Steam at least once?

I have bought FNV from GoG and yes I have ran the launcher plenty of times but did not open the game itself, only launcher.

**Comment by pStyl3** [comment]
In LOOT's settings, try to insert the `Install Path` by hand.
![grafik](https://user-images.githubusercontent.com/10406657/134426416-a91d2c72-96dc-48b9-8a72-e084938b4267.png)

**Comment by abysskeeper** [comment]
I can't believe it! It's fixed!!! Thank you so much. I think the the problem comes from the fact that my Fallout New Vegas is directly inside my C: Drive instead of program files or whatever. Again, I am greatful beyond measure!
