### ISSUE TITLE
A couple of rules LOOT gets wrong.

### ISSUE THREAD

**Issue by Shrimpfren** [loot/falloutnv#246]
1. [A crime against nature](https://www.nexusmods.com/newvegas/mods/67853) must load after [Cannibal Reborn](https://www.nexusmods.com/newvegas/mods/64789). It is noted in the descriptions, and again in-game if you get them in reverse.

2. A series of Lucky 38 altering mods must be placed in a specific order to work, they complement each other, 2 of the three recommend the others, and there is a specific load order noted and acknowledged by all three authors to get it to work properly.

[Better Strip View](https://www.nexusmods.com/newvegas/mods/73261) => [Strip Lights Region Fix](https://www.nexusmods.com/newvegas/mods/73596) => [Lucky 38 Lights Redone](https://www.nexusmods.com/newvegas/mods/73273)

Respectively, there are patches to each mod that must also be placed before moving on to the next mod.
([Strip Lights Region Fix author's note](https://imgur.com/a/4DiZcrx))

**Comment by sibir-ine** [comment]
@Shrimpfren All of the necessary changes have been made, please update your masterlist.

**Comment by Shrimpfren** [comment]
> @Shrimpfren All of the necessary changes have been made, please update your masterlist.

Thank you.
