### ISSUE TITLE
Wrong plugin filename for FNV Realistic Wasteland Lighting - Darker Nights

### ISSUE THREAD

**Issue by RePlay-be** [loot/falloutnv#26]
Link to the Nexus mod page: http://www.nexusmods.com/newvegas/mods/52037/

**Concerned plugins:**
* FNV Realistic Wasteland Lighting - Full.esp
* FNV Realistic Wasteland Lighting - Darker Nights.esp

From what I understand, the *Darker Nights* optional plugin of *FNV Realistic Wasteland Lighting* has the wrong filename in the Fallout New Vegas masterlist. I've noticed this issue because the optional plugin should be loaded after the main plugin, however this doesn't happen when sorting with LOOT. After investigating the masterlist, I've found the following plugin name which I believe corresponds to the *Darker Nights* plugin: **FNV RWL Darker Nights.esp**. However the correct filename should be: **FNV Realistic Wasteland Lighting - Darker Nights.esp**. Inspecting this plugin entry reveals that it has the same priority as the main plugin, but it has the main plugin listed in the *after* metadata. Thus fixing the filename should fix the problem.

However, I still couldn't get it to work after attempting to fix this myself by: making a local masterlist copy and changing the filenames, and then using this local copy in LOOT. After sorting my plugins with my local masterlist, the *Darker Nights* plugin had no metadata. The filenames were however an exact match. Using the "live" masterlist, the plugin also showed no metadata in LOOT. Why this doesn't work is beyond me so I've opted to create this issue because I'm not too familiar with LOOT.

Also note that there are in total three references to the plugin that need to be fixed: its own plugin entry, and as *inc* metadata for **FNV Realistic Wasteland Lighting - ENB Full.esp** and **FNV Realistic Wasteland Lighting - ENB No DLC.esp**.

**Comment by Freso** [comment]
Was it *ever* called `FNV RWL Darker Nights.esp` though? Ie., is there a chance some people out there have a version with the file name `FNV RWL Darker Nights.esp`?

**Comment by Freso** [comment]
I've commented on the commit that added `FNV RWL Darker Nights.esp` and will wait for feedback from there: https://github.com/loot/falloutnv/commit/5a4f6f31#commitcomment-14555462

**Comment by RePlay-be** [comment]
That's a good question, and I had wondered the same. Looking through the old versions of FNV RWL I didn't see any older versions of the Darker Nights plugin. However googling the exact filename `FNV RWL Darker Nights.esp` did show a few results, which leads me to believe that, yes, that was the filename in the (distant) past: [https://www.google.com/search?q="FNV RWL Darker Nights.esp"](<https://www.google.com/search?q="FNV RWL Darker Nights.esp">).

**Comment by Freso** [comment]
Alright. I added `FNV Realistic Wasteland Lighting Darker Nights.esp` as a new, separate entry and added an "this mod is obsolete" message to `FNV RWL Darker Nights.esp` (though not an `inc` entry for `FNV Realistic Wasteland Lighting Darker Nights.esp` - if someone feels this needs to be added too, go ahead or let me know). Let me know if it works now, and re-open if it doesn't. :)

**Comment by RePlay-be** [comment]
I'm not sure if you made a mistake or not, but I noticed that you committed to the `master` branch and not `v0.8`. The guide for contributing only mentions
>make sure that you're working on the correct branch for LOOT's latest release.

which I assumed meant `v0.8` for the latest version of LOOT.

Additionally you forgot the hyphen for the new, separate entry. :)

**Comment by Freso** [comment]
That was very much my mistake, yes. I've merged master into v0.8 now, so try again. It *should* work now. :)

**Comment by Freso** [comment]
> Additionally you forgot the hyphen for the new, separate entry. :)

Which entry?

**Comment by RePlay-be** [comment]
On the `v0.8` branch, on line 4631:
`- name: 'FNV Realistic Wasteland Lighting Darker Nights.esp'`
should be:
`- name: 'FNV Realistic Wasteland Lighting - Darker Nights.esp'`

**Comment by Freso** [comment]
Curses! Should be fixed now with 3d2d0521e28d796cdba0f8c25b246aad8a290855.

**Comment by RePlay-be** [comment]
Excellent, it worked!

By the way, after further testing I believe my LOOT is using a cached copy of the masterlist as opposed to my local copy. Where would be an appropriate place to discuss this further? (Or development/contribution questions about LOOT in general)

**Comment by WrinklyNinja** [comment]
> By the way, after further testing I believe my LOOT is using a cached copy of the masterlist as opposed to my local copy. Where would be an appropriate place to discuss this further? (Or development/contribution questions about LOOT in general)

You can open an issue in the [loot/loot tracker](https://github.com/loot/loot/issues), or use the [forum thread](http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/). Have you remembered to change LOOT to use your local repository, or disable automatic masterlist updating so that it doesn't overwrite the copy you replaced LOOT's copy with?

**Comment by Freso** [comment]
Also, you're also welcome to come to the IRC chat channel - just hang around there and wait for me to stop by. You came on tonight at 2 AM my time, so I was fast asleep at the time. :)
