### ISSUE TITLE
Metadata Issue - Error code 14

### ISSUE THREAD

**Issue by Izen-san** [loot/falloutnv#27]
LOOT error for "Fallout: New Vegas"

Masterlist Revision c30b9bd
Masterlist Date 2016-02-04
Active Plugins: 97
Dirty Plugins: 5  (Cleaned DLC ESMs, but apparently CRCs are not recognized)
Total Plugins: 98

Nexus Mod: http://www.nexusmods.com/newvegas/mods/37082/?

Error code: 14; Failed to sort plugins. Details: Cyclic interaction detected between plugins "BlackWolf Backpack.esp" and "BlackWolf Backpack - Vendor Script Replenish.esp". Back cycle: BlackWolf Backpack - Vendor Script Replenish.esp, BlackWolf Backpack.esp
[Uploading LOOTDebugLog.txt…]()

**Comment by Ortham** [comment]
Sorry for the delay, but it looks like you submitted your post before the log file finished uploading, can you try again?

**Comment by Ortham** [comment]
Actually, scratch that, it's a simple case of the two plugins requiring each other in the metadata.

Fixed in dc8fe33ec3d29f9bdf065b2a3e3974700002ad41.
