### ISSUE TITLE
NVR and NVR-Electro-City Patch cyclic interaction error

### ISSUE THREAD

**Issue by EvilOssie** [loot/falloutnv#31]
I'm using LOOT for my new NV build for the first time; I get an error message during the sort process (NVR- is from New Vegas Restoration)...

> ERROR
> Failed to sort plugins. Details: Cyclic Interaction detected between plugins "NVR-Strip.esm" and "NVR-Electro-City_Patch.esp". Back cycle: NVR-Electro-City_Patch, NVR-Strip.esm.

Afterward, the sort process apparently stops there. I have absolutely no idea what that means, aside from it not wanting to sort those two...can someone help here, please? Google is no help at all.

[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/490808/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/falloutnv/files/490809/CEFDebugLog.txt)

**Comment by Ortham** [comment]
I've edited your comment to include your original forum thread post for context, and taking a look at your log now.

**Comment by Ortham** [comment]
Well, the reason it's failing is that `NVR-Strip.esm` is a master file and `NVR-Electro-City_Patch.esp` is not, but you have load after metadata telling the former to load after the latter, which can't be done.

**Comment by EvilOssie** [comment]
Crap...I would have sworn that I removed that entry. Only thing I can guess (recall that I said that I'm still learning LOOT) is that I forgot to save the edit after doing it.

My (kinda embarrassing) bad, and thank you, sir.
- EDIT - As long as I have your attention...LOOT tosses warnings about Project Nevada - Core.esm and oHUD.esm needing NVSE installed; I do have the current stable NVSE but I use the modded FNV4GB loader, available on the NVSE site, in place of the default NVSE loader. I ignore the warning since everything seems to be fine (in-game console command for NVSE shows that its installed, etc), and I mention it now only in case you were somehow not aware of LOOT not recognizing the 4gig launcher for what it is and throwing up essentially a false warning.

**Comment by Ortham** [comment]
> EDIT - As long as I have your attention...LOOT tosses warnings about Project Nevada - Core.esm and oHUD.esm needing NVSE installed; I do have the current stable NVSE but I use the modded FNV4GB loader, available on the NVSE site, in place of the default NVSE loader. I ignore the warning since everything seems to be fine (in-game console command for NVSE shows that its installed, etc), and I mention it now only in case you were somehow not aware of LOOT not recognizing the 4gig launcher for what it is and throwing up essentially a false warning.

Could you open a new issue for that and provide the warning message text?

**Comment by EvilOssie** [comment]
Sure.
