### ISSUE TITLE
LOOT not recognizing NVSE 4GB launcher

### ISSUE THREAD

**Issue by EvilOssie** [loot/falloutnv#32]
I get this message for both Project Nevada - Core.esm and oHUD.esm. I have the current NVSE installed and running correctly, but I use the modded 4GB launcher from the NVSE page rather than the default NVSE launcher.

![loot error](https://cloud.githubusercontent.com/assets/7400914/18969038/55c427ec-8640-11e6-9a45-d96bef6f96bb.jpg)

**Comment by Freso** [comment]
I don't know how we'd detect that though.

**Comment by EvilOssie** [comment]
I should have added before that LOOT does not toss that message for other mods in my list that require NVSE (offhand, both JIP Selective Fire and Willow come to mind...there are probably a few more as well); it only shows for those two. Given that, it appears that it is being detected at times and/but not detected other times.

I bring it up mainly to pass the info on, in case it wasn't already known (I just ignore the message after I verified that NVSE is in fact functioning in my game).

**Comment by EvilOssie** [comment]
A few hours later...
I didn't mean to close this. I didn't even know that I'd closed it until just now. Sorry 'bout that.

**Comment by Ortham** [comment]
Surely if you're using the 4 GB launcher that `nvse_loader.exe` should still be in your FalloutNV folder?

**Comment by EvilOssie** [comment]
Just now dbl-checked and nope...only the NVSE-modded 4 GB launcher. The NVSE page says to use it in place of the regular one. It's actually the one available below; I don't know what's been done to it so it recognizes both the LAA and NVSE, tho.
- http://www.nexusmods.com/newvegas/mods/35262/?

**Comment by Freso** [comment]
@WrinklyNinja I think what mod 35262 does is that it tells the Skyrim/FO:NV .exe to load some .dll's. Since what `nvse_loader.exe` does is basically to load the NVSE .dll (I think?), you don't really need that if the game's .exe is doing that already.

@EvilOssie Do you have any nvse .dll's in your game folder?

**Comment by Ortham** [comment]
In that case, it's probably best to change the file being looked for to one of the DLLs, but I'm not sure which is best. AFAIK players don't need the editor DLL, and I think New Vegas might have been available in a non-Steam version, so the steam loader DLL isn't always necessary either. 

Do German players need to rename the `nvse_1_4ng.dll` to `nvse_1_4.dll`, or do they use it as-is? The readme just says to copy all DLLs across, but the non-gore and normal DLLs are the same size as one another, so I guess only one is needed...

**Comment by EvilOssie** [comment]
@Freso Yes, the DLLs are there.
