### ISSUE TITLE
my bad

### ISSUE THREAD

**Issue by howiebabey** [loot/falloutnv#36]

**Comment by howiebabey** [comment]
i disabled my firewall to post this im using a ps4 wireless controller with a usb blue tooth adapter it syncs fine  i have mods if ya want to see my mod list just ask im using loot tool and nexus mod manager

**Comment by howiebabey** [comment]
anyone?

**Comment by WilliamImm** [comment]
Wow, that is absolutely not an issue with LOOT. Check Inputmapper for issues with the game. LOOT has absolutely no relation to this.

Closing.
