### ISSUE TITLE
LOOT wont load

### ISSUE THREAD

**Issue by itstragicz** [loot/falloutnv#39]
[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/2129457/LOOTDebugLog.txt)
Im not new to LOOT at all, ive just never had any problems using it, it wont seem to load for FO:NV as you can see by the debug log, i havent been able to find any fixes for this, if there already is then that would be great if you could point me in that direction. Im using Win10 pro if it helps.
Thanks.

**Comment by itstragicz** [comment]
and i am aware that im missing a couple masters, im in the process of installing those.

**Comment by itstragicz** [comment]
I looked through the debug log and it looks like new vegas bounties III has some compatibility issues, disabled that through FMO and it worked fine. closing the ticket.

**Comment by Ortham** [comment]
Looks like a duplicate of loot/loot#858, this won't be a problem in the next release of LOOT.
