### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/falloutnv#40]
I would like to relicense the LOOT masterlists/repositories to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit them to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

@WrinklyNinja, @William-Imm, @Freso, @Sharlikran, @EssArrBee, @egocarib, @niveuseverto, @SilentSpike, @abiel0530, @shadowslasher410, @RiderSystems (these are [all the contributors listed on GitHub](https://github.com/loot/falloutv/graphs/contributors)) if you agree with moving to this much more free license, please write a comment here confirming this.

~~@WrinklyNinja If you're able to get a list of BOSS contributors prior to the conversion that haven't been mentioned above, that'd be great. :)~~

<details>
<summary>Agreed LOOT contributors</summary>

- [x] @WrinklyNinja
- [x] @William-Imm
- [x] @Freso
- [x] @Sharlikran
- [x] @EssArrBee
- [x] @egocarib
- [x] @niveuseverto
- [x] @SilentSpike a.k.a. kymckay
- [x] @RiderSystems
- [x] @shadowslasher410
- [x] @sibir-ine 
- [x] @RowanSkie 
- [x] @Infernio 
- [x] Zack Layton `<SYNStack at users.noreply.github.com>` a.k.a. @ZackArmitage
- [x] darthbdaman `<stevenefranklin at gmail.com>` a.k.a. @darthbdaman
- [x] DeusGladiorum ([Nexus](https://www.nexusmods.com/users/5402598))
- [x] ~~@abiel0530~~ Clean-room reimplemented contributions
- [x] ~~MothHeart `<kristianityofficial+4 at gmail.com>`~~ Clean-room reimplemented contributions
</details>

<details>
<summary>Agreed BOSS contributors not already mentioned</summary>

- [x] @valda
- [x] @Arthmoor
- [x] @TokcDK
- [x] @noxwyll
- [x] @deathssoul
- [x] @spaceoden
- [x] Alexander Filippov `<a.filippov at technodeep.net>`
- [x] Loucifer `<lewisjustice at gmail.com>`
- [x] Red Eye `<alex.redeye at gmail.com>`
- [x] Malonn ~~`<marklonn at gmail.com>`~~ (Email bounced) ([AFK](https://www.afkmods.com/index.php?/profile/8342-malonn/)) ([Nexus](https://www.nexusmods.com/users/375371)) a.k.a. @MalonnBethesda
- [x] ~~Skyline `<mariolam9462 at gmail.com>`~~ Clean-room reimplemented contributions
</details>

Once/if everyone accepts, I'll change the license.

**Comment by Ortham** [comment]
The BOSS contributors not mentioned above are:

- @valda
- @Arthmoor
- @TokcDK

Also the following people who I couldn't find on GitHub:

```
Space Oden69 <jacksonleist@gmail.com>
Loucifer <lewisjustice@gmail.com>
Skyline <mariolam9462@gmail.com>
Malonn <marklonn@gmail.com>
noxwyll <wyll@live.de>
Red Eye <alex.redeye@gmail.com>
Torrello <torrello.boss@gmail.com>
menduki <menduki@yandex.ru>
deaths_soul (MCP) <NULL>
Alexander Filippov <a.filippov@technodeep.net>
```

**Comment by Arthmoor** [comment]
No problem with this.

**Comment by valda** [comment]
No problem.

**Comment by JakeRider** [comment]
@RiderSystems is my old account, I'm embarrassed to say I've forgotten the password. I don't have a problem with this, and if you need me to, I can find a way back into that old account.

**Comment by Freso** [comment]
@JakeRider I trust your word on it, but if possible and not too much trouble, it'd be great to get confirmation from the "right" account too. :)

**Comment by RiderSystems** [comment]
@JakeRider is me, sorry about the confusion. I support changing the license.

**Comment by Ortham** [comment]
I agree.

**Comment by kymckay** [comment]
I agree.

**Comment by Sharlikran** [comment]
+1

**Comment by niveuseverto** [comment]
Agreed!

**Comment by TsunaMoo** [comment]
Confirmed.

**Comment by Freso** [comment]
I sent a message on Nexus to Malonn.

**Comment by egocarib** [comment]
I support this.

**Comment by deathssoul** [comment]
CC0 is fine by me for the metadata: https://github.com/loot/oblivion/issues/24#issuecomment-410244509

:)

**Comment by Freso** [comment]
@spaceoden gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410348382

**Comment by WilliamImm** [comment]
No issues with those (formerly William-Imm)

**Comment by pStyl3** [comment]
@TokcDK agreed for Skyrim's and Oblivion's masterlist. I've ticked his checkbox for Fallout New Vegas aswell.

**Comment by pStyl3** [comment]
@EssArrBee
@abiel0530
@shadowslasher410

Sorry to ping you again, but if time permits, could you evaluate the above mentioned situation?
Thank you.

**Comment by EssArrBee** [comment]
I have no issue with this. I haven't been active in over a year, so no one has to bother asking me.

**Comment by RowanSkie** [comment]
I agree with the motion.

**Comment by sibir-ine** [comment]
Infernio agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817335752 (posting to keep track).

**Comment by sibir-ine** [comment]
@shadowslasher410 agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817338963.

**Comment by sibir-ine** [comment]
@abiel0530 

If you're still around, could you please read this issue & state whether you agree?

**Comment by sibir-ine** [comment]
Loucifer agreed via email:
> As it seems you want a formal decision, I approve any change needed, and release all rights to anything that may be considered to be my copyright for this application. 
> 
> I do not have a github account, so let this email serve as my comments.

**Comment by sibir-ine** [comment]
Red Eye agreed via email:
> I'm fine with it.

**Comment by Ortham** [comment]
Here are links to view the outstanding BOSS contributors' contributions (in the BOSS masterlist):

- [Skyline](https://github.com/boss-developers/falloutnv/commits/master?author=mariolam9462@gmail.com): 2 pages of commits, some metadata that may have been kept in the LOOT masterlist ([TODO](https://gist.github.com/sibir-ine/26e7aa8f8d547e54c72aa668ffd4a2f3))
- ~~[Torrello](https://github.com/boss-developers/falloutnv/commits/master?author=torrello.boss@gmail.com)~~: only whitespace changes, so Torrello's agreement isn't required as whitespace wasn't preserved when converting the BOSS masterlists.
- ~~[Malonn](https://github.com/boss-developers/falloutnv/commits/master?author=marklonn@gmail.com): one page of commits, some metadata that may have been kept in the LOOT masterlist~~ Agreed

Outstanding LOOT contributors' contributions:
- [MothHeart](https://github.com/loot/falloutnv/commits/v0.15?author=kristianityofficial%2B4@gmail.com) ([mothheart](https://github.com/loot/falloutnv/commits/v0.15?author=52017078%2Bmothheart@users.noreply.github.com), [Dr. Gutfuck LLC](https://github.com/loot/falloutnv/commits/v0.15?author=kristianityofficial@gmail.com), [Dr. Gutfuck LLC](https://github.com/loot/falloutnv/commits/v0.15?author=40531868%2Bgutfuckllc@users.noreply.github.com)): about 1 page of commits ([TODO](https://gist.github.com/sibir-ine/4dce7468548c48d1eaa66f396a1689bd))

**Comment by sibir-ine** [comment]
abiel0530 has 2 [changes](https://github.com/loot/falloutnv/commit/5f9a8a6d9de4fe5541e400122e037d94b0816ef1) that are somewhat still present:

https://github.com/loot/falloutnv/blob/8991dc93e3ef560abac6c572057d551a6d351df6/masterlist.yaml#L5854
https://github.com/loot/falloutnv/blob/8991dc93e3ef560abac6c572057d551a6d351df6/masterlist.yaml#L5856-L5861
https://github.com/loot/falloutnv/blob/8991dc93e3ef560abac6c572057d551a6d351df6/masterlist.yaml#L5865-L5870

I say somewhat present as these entries have both been recleaned by @pStyl3, so it depends on if we count that as sufficiently replacing abiel's original contributions. Both mods ([variant](https://www.nexusmods.com/newvegas/mods/58871/) & [betsy](https://www.nexusmods.com/newvegas/mods/59265/)) are still around, & neither have been updated since last cleaned.

**Comment by Infernio** [comment]
I'm of the opinion that cleaning data can't be copyrighted, because there's no originality in it. Everyone will come up with the exact same report, that's the whole point of cleaning.
So simply recleaning every plugin whose cleaning data came from individuals that haven't agreed is sufficient for replacing their contributions, in my opinion.

Edit: if you want to read more about the requirement of originality: https://guides.lib.umich.edu/copyrightbasics/copyrightability

**Comment by sibir-ine** [comment]
@Infernio That seems sensible to me. @Ortham, do you feel that that's enough justification to say we don't need abiel's agreement?

**Comment by Ortham** [comment]
Without getting into deciding if contributing data like cleaning data is sufficiently creative (though I'd say it's not, whereas message text probably would be), if abiel0530's contribution was the addition of cleaning data and pStyle replaced that data, then abiel0530's contribution is no longer present so we don't need their agreement.

**Comment by sibir-ine** [comment]
~~WIP TODO list for Malonn's contributions.~~

**Comment by malonn23** [comment]
No problem by me.  I forgot I contributed to BOSS...

**Comment by sibir-ine** [comment]
> 
> 
> No problem by me. I forgot I contributed to BOSS...

Thank you so much for responding!

**Comment by sibir-ine** [comment]
@darthbdaman @ZackArmitage

If you guys are still around, could you please read this issue & state whether you agree?

**Comment by cvaylen** [comment]
I agree

**Comment by darthbdaman** [comment]
Go ahead

**Comment by sibir-ine** [comment]
DeusGladiorum made [1 change](https://github.com/loot/falloutnv/commits/v0.15?author=DeusGladiorum@users.noreply.github.com) to the masterlist. `MMUE-CP-EVE.esp` is the EVE patch found on MMUE's [page](https://www.nexusmods.com/newvegas/mods/45104). Considering we have a message directing users to YUP since (I'm assuming) MMUE is outdated, we can just drop the change without further investigation.

**Comment by sibir-ine** [comment]
[TODO](https://gist.github.com/sibir-ine/4dce7468548c48d1eaa66f396a1689bd) for MothHeart's contributions.

**Comment by TsunaMoo** [comment]
@sibir-ine MMUE is considered finished not outdated as FNV isn't in development since ages. That user is probably Al99 at nexus.

**Comment by TsunaMoo** [comment]
I am sick of this constant harrassment campaign about MMUE coming from Yukichigai. It been 6 years and there is still constant badmouthing coming through him.

I'll delete MMUE, just make this crap stop.

**Comment by sibir-ine** [comment]
@TsunaMoo I'm sorry, I was unaware of the situation. If MMUE is still fine to use, we can remove the `*useInstead` message & add an incompatibility message between MMUE & YUP if appropriate.

Thank you for pointing me to their Nexus account as well.

**Comment by TsunaMoo** [comment]
@sibir-ine Thanks but I really just want the situation to stop. I checked the comments and see they are full of hate, toxicity and more since a couple months. I don't intend to have MMUE be public again . I just wanna not deal with that.

Feel free to remove MMUE entirely.
I am being bullied into this but I don't have the energy to fight it.

**Comment by sibir-ine** [comment]
@TsunaMoo I understand. You could also hand the mod over to the [Nexus Care Taker](https://www.nexusmods.com/skyrim/users/1234042), but I understand if you'd prefer keeping the mod hidden.

**Comment by sibir-ine** [comment]
[TODO](https://gist.github.com/sibir-ine/26e7aa8f8d547e54c72aa668ffd4a2f3) for Skyline's contributions.

**Comment by sibir-ine** [comment]
@TsunaMoo Sorry, just to clarify, which user is Al99 on Nexus? MothHeart or DeusGladiorum? I found [this account](https://www.nexusmods.com/users/5402598), so I'm assuming that's DeusGladiorum & Al99 is MothHeart.

**Comment by sibir-ine** [comment]
_Removed at the request of the contributor_

**Comment by sibir-ine** [comment]
DeusGladiorum agreed via email:

> Hello,
> 
> I'm Deus Gladiorum... I apologize for the extremely late response, but I have no issue with any changes made to this project whatsoever.
