### ISSUE TITLE
NV Do Not Clean Mods

### ISSUE THREAD

**Issue by ghost** [loot/falloutnv#41]
https://www.nexusmods.com/newvegas/mods/51664
- [x] YUP - Base Game + All DLC.esm
Do not clean, restores skeletons that OWB erroneously changed

-----

https://www.nexusmods.com/newvegas/mods/56625
- [x] Uncut Skeletons.esp
Do not clean, restores skeletons that OWB erroneously changed

-----

https://www.nexusmods.com/newvegas/mods/65052
- [x] WMIM.esp
Do not clean, reverts forms to vanilla which other mods edit which is required for the 771 mesh changes to function correctly
Needs bash tags

incompatible with EVE, WMX, WME, WRP

**Comment by pStyl3** [comment]
I'm working on this.  According to the mod description`Weapon Mesh Improvement Mod` is now fully compatible with `WRP`. The plugin is also called `WMIMNV.esp` now and not `WMIM.esp`.
