### ISSUE TITLE
TTW Notes

### ISSUE THREAD

**Issue by MacSplody** [loot/falloutnv#46]
### Baseline mod list

- 4GB Patch
- NVSE 5.1b4
- JIPLN
- NVSR
- NVAC
- Tale of Two Wastelands 3.1
- TTW YUP
- A World of Pain (usually)
- Darnified UI (custom edit)
- MCM
- CASM with MCM
- FOVSlider
- JIP Improved Recipe Menu
- The Weapon Mod Menu
- Tutorial Killer
- Enhanced Item Info
- BLEED (usually)
- TTW Bobbleheads
- TTW Equipment Restoration
- TTW Perk Per Level
- TTW No Karma Followers
- TTW Quick Start
- TTW VATS
- TTW XP Reduction
- Blur Remover (custom)

**Comment by MacSplody** [comment]
### Baseline Load Order

1. FalloutNV.esm
2. DeadMoney.esm
3. HonestHearts.esm
4. OldWorldBlues.esm
5. LonesomeRoad.esm
6. GunRunnersArsenal.esm
7. Fallout3.esm
8. Anchorage.esm
9. ThePitt.esm
10. BrokenSteel.esm
11. PointLookout.esm
12. Zeta.esm
13. CaravanPack.esm
14. ClassicPack.esm
15. MercenaryPack.esm
16. TribalPack.esm
17. TaleofTwoWastelands.esm
18. DarNifiedUINV.esp
19. CASM with MCM.esp
20. Better Pickup Prompt.esp
21. Project Nevada - Equipment.esm
22. NVWillow.esp
23. Sortomatic.esm
24. SomeguySeries.esm
25. Interior Lighting Overhaul - Core.esm
26. Interior Lighting Overhaul - L38PS.esm
27. Project Nevada - Core.esm
28. Project Nevada - Cyberware.esp
29. TTW Redesigned.esm
30. Project Nevada - Rebalance.esp
31. Project Nevada - Extra Options.esm
32. The Mod Configuration Menu.esp
33. Clarity - TTW.esp
34. FastSleepNV.esp
35. DYNAVISION 3.esp
36. Easy Hacking.esp
37. TTW_NoKarmaDCFollowers.esp
38. TTW_SpeechChecks.esp
39. TTWOptions.esp
40. ImmersiveRecoil.esp
41. JIP Improved Recipe Menu.esp
42. JIP MiniMap.esp
43. Project Nevada - All DLC.esp
44. Project Nevada - Cyberware Additions.esp
45. Project Nevada - Rebalance Complete.esp
46. HZSmoothLight.esp
47. FOVSlider.esp
48. MoriartysTestFix.esp
49. ttwdlcmusic.esp
50. BLEED.esp
51. Delay DLC - TTW.esp
52. dD - Enhanced Blood.esp
53. JIP Companions Command & Control.esp
54. NVWillowRebalance.esp
55. MTB.esp
56. Faster Terminals.esp
57. Delay Level Up - Stealth Suit Fix.esp
58. brotherhoodpresence.esp
59. TTWStashPackDistribution.esp
60. Delay Level Up.esp
61. WeaponModsExpanded.esp
62. WMX-ArenovalisTextures.esp
63. Flora Overhaul.esp
64. ammoingredientsloot.esp
65. Vurt's WFO.esp
66. LootMenu.esp
67. NewVegasBounties.esp
68. NewVegasBountiesII.esp
69. TTW - Distributed Necklaces and Chains.esp
70. STFU.esp
71. Interior Lighting Overhaul.esp
72. TTW Perks and Home Markers Essential.esp
73. NVWillow - Project Nevada Rebalance.esp
74. ShilohDS-Color Maps and Icons.esp
75. Quick Grenade Hotkey.esp
76. WMIMNV.esp
77. The Weapon Mod Menu.esp
78. PittGalStatsFix.esp
79. LiveDismember.esp
80. PittGalStatsFix - DarnUI.esp
81. Type 6.esp
82. Replace FeralGhoul to CrazyMrHandy.esp
83. Graveyard Radio.esp
84. FeralGhoulsToHandyFNV.esp

**Comment by cvaylen** [comment]
Entire list needs to be scrapped, doesn't correspond with 3.2 compatibility at all. I have two lists here of commonly used and compatible 3.2 mods:

https://wiki.synstack.org/books/mod-index/page/ttw-32-essential-mods
https://wiki.synstack.org/books/tale-of-two-wastelands/page/project-nevada-alternatives

**Comment by Freso** [comment]
I think TTW are maintaining their own LOOT masterlist now, no? If so, the FNV masterlist should probably just give a `warning` if any TTW specific plugins are found and say to use the TTW masterlist instead and not bother too much about trying to sort it?

**Comment by cvaylen** [comment]
Probably a miscommunication, TTW isn't doing their own.

**Comment by ghost** [comment]
What is this list even trying to say? I'm confused.

**Comment by MacSplody** [comment]
Closing as it was just for notes.
