### ISSUE TITLE
Update or Remove dead URLs

### ISSUE THREAD

**Issue by pStyl3** [loot/falloutnv#68]
```
Gun Runners' Arsenal Disabled.esp
Gun Runners' Arsenal Disabled - TTW.esp
```
https://www.nexusmods.com/newvegas/mods/59615

```
NewVegasUncut.esm
NewVegasUncut - TTW.esm
NewVegasUncut - New Vegas Bounties.esp
NewVegasUncut - New Vegas Bounties II.esp
NewVegasUncut - Inheritance.esp
NewVegasUncut - Russell.esp
NewVegasUncut - NewVegasKiller.esp
NewVegasUncut - NewVegasBountiesIII.esp
NewVegasUncut - Someguy Series.esp
```
https://github.com/Uncut/Uncut

```
MMUE - Deutsch.esp
```
https://modworkshop.net/mydownloads.php?action=view_down&did=1

```
Power Armor Distribution Overhaul.esp
Power Armor Distribution Overhaul - TTW.esp
Power Armor Distribution Overhaul - MMM.esp
Power Armor Distribution Overhaul - NVCE.esp
Power Armor Distribution Overhaul - JSawyer.esp
Power Armor Distribution Overhaul - TTW_OutcastTrading.esp
Power Armor Distribution Overhaul - Unoctium.esp
```
https://www.nexusmods.com/newvegas/mods/59677

```
FNV Realistic Wasteland Lighting - Enhanced.esp
TTW Realistic Wasteland Lighting - Enhanced.esp
FNV TTW RWLE - NVBII Patch.esp
```
https://www.nexusmods.com/newvegas/mods/59591

```
Fix the lights and Crap be gone.esp
SupahWeapons.esp
```
https://www.nexusmods.com/newvegas/mods/60089 (#21)

**Comment by pStyl3** [comment]
The mentioned plugins doesn't seem to be available anywhere else. So delete the mentioned dead `url` entries from the masterlist.

**Comment by pStyl3** [comment]
Instead of outright removing the individual `url` rows, replace them with `url: []`.
The empty `[]` will indicate from now on, that the plugin in question once had a url attached to it, which later was found to be dead and as such the plugin no longer has a source.

**Comment by sibir-ine** [comment]
Reopening this as it would be best to remove the metadata of plugins that are no longer publicly available. See https://github.com/loot/falloutnv/pull/126#issuecomment-788234028.
