### ISSUE TITLE
Would it be possible to do the following:

### ISSUE THREAD

**Issue by RowanSkie** [loot/falloutnv#88]
1. Add New California group for Fallout: New California (or)
2. Change TTW Group name to Overhaul Group.

I'm asking on behalf of some of the volunteers who are working on FNC because some of our users get confused.

**Comment by MacSplody** [comment]
> 1. Add New California group for Fallout: New California (or)
> 2. Change TTW Group name to Overhaul Group.
>
> I'm asking on behalf of some of the volunteers who are working on FNC because some of our users get confused.

Option two would be preferable, I'll have to do some testing of the current sorting first.
I think it would be best to set up the early groups so they'll work for TTW and FNC or any similar mods.

**Comment by MacSplody** [comment]
@RowanSkie Done in https://github.com/loot/falloutnv/commit/bcbce31a1f029ff70dee4952818e46bf14645fc1
